version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/dhrvjha
      - static_volume:/home/dhrvjha/web/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/dhrvjha/web/staticfiles

volumes:
  static_volume:
