version: '3.8'

services:
  web:
    image: dhrvjha/dhrvjha_web
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
