name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker compose build
    - name: Run Docker container
      run: docker compose up -d
    - name: Wait for Django to start
      run: docker compose exec web python manage.py wait_for_db
    - name: Run Django tests
      run: docker compose exec web python manage.py test
    - name: Stop Docker container
      run: docker compose down
