name: Release CD 

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set Up QMEU Action
      uses: docker/setup-qemu-action@v3
    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_USER_TOKEN }}
    - name: Set Image Tag
      run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_USER_NAME }}-web:${{ env.IMAGE_TAG }},${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_USER_NAME }}-web
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./nginx/Dockerfile.prod
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_USER_NAME }}-nginx:${{ env.IMAGE_TAG }},${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_USER_NAME }}-nginx
    - name: Push to release branch
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email actions@github.com
        git switch origin/build
        git merge origin/master
        git push origin build 
