
name: Release CD 

on:
  push:
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker hub
      run: echo "${{secrets.DOCKER_USER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER_NAME}} --password-stdin
    - name: Set Image Tag
      run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
    - name: Build Docker image
      run: docker compose -f docker-compose.prod.yml build
    - name: Push Docker Images
      run: | 
        docker push dhrvjha/dhrvjha-web:${IMAGE_TAG}
