name: Release CD 

on:
  push:
    branches: [ "release" ]
  pull:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set Up QMEU Action
      uses: docker/setup-qemu-action@v3
    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_USER_TOKEN }}
    - name: Set Image Tag
      run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
    - name: Image Name
      run: echo ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_USER_NAME }}-web:${IMAGE_TAG}
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_USER_NAME  }}-web:${{ env.IMAGE_TAG }}
